[FEAT] 엔티티 설계
DGU-ICE-22/RoomCatcher_BE pull request #3
Opened 2024-06-30 16:06 UTC by eeddiinn

## 📌 연관된 이슈

closed #2 

## 📝 작업 내용

![image](https://github.com/DGU-ICE-22/RoomCatcher_BE/assets/137388764/042914e7-ffd0-4e96-b862-ebee08b854ca)
위 ERD를 참고하여 9개 엔티티 구현 ! 
- User, UserProduct, UserTag, UserType, UserTypeTag 엔티티 설계 
- Tag 엔티티 설계
- Question 엔티티 설계
- Product, ProductTag 엔티티 설계

### 스크린샷 (선택)

## 💬리뷰 요구사항(선택)
- 오타나 틀린 부분 없는지 꼼꼼히 봐주세욤 🙇‍♀️

2024-07-01 05:56 UTC, 5hseok requested changes
리뷰 읽어주시구 id 통일만 해주세요. 
@eeddiinn 
#3

2024-07-01 05:56 UTC, 5hseok commented on src/main/java/com/roomcatcher/RoomCatcher/domain/Product.java
> +    private Long Id;
여기도 소문자로 id로 통일하는 게 낫을 듯

2024-07-01 05:56 UTC, 5hseok commented on src/main/java/com/roomcatcher/RoomCatcher/domain/ProductTag.java
> +    private Long Id;
여기두요

2024-07-01 05:56 UTC, 5hseok commented on src/main/java/com/roomcatcher/RoomCatcher/domain/Tag.java
> +    private List<UserTag> userTags;
여기서 아래 productTags와 userTypeTags처럼 초기화를 하지 않은 이유가 있나요?

2024-07-01 05:56 UTC, 5hseok commented on src/main/java/com/roomcatcher/RoomCatcher/domain/User.java
> +    @JoinColumn(name = "userTypeId")
우리 ERD에는 typeId로 되어있긴 하던데, 그냥 요렇게 설정하는걸로 할까요

2024-07-01 05:56 UTC, 5hseok commented on src/main/java/com/roomcatcher/RoomCatcher/domain/Tag.java
> +    @Column(name = "tagId")
ERD에서는 그냥 id라고만 되어있는데, tagId로 수정한 센스가 굿이네

2024-07-01 07:32 UTC, 5hseok commented on src/main/java/com/roomcatcher/RoomCatcher/domain/Product.java
> +    @Column(nullable = false)
Column에 길이 안 써도 되나? length = 20 이런거

2024-07-01 13:34 UTC, eeddiinn commented on src/main/java/com/roomcatcher/RoomCatcher/domain/Tag.java
> +    private List<UserTag> userTags;
헉 ..!!! 그러네요 수정하겠습니당

2024-07-01 13:36 UTC, eeddiinn commented on src/main/java/com/roomcatcher/RoomCatcher/domain/User.java
> +    @JoinColumn(name = "userTypeId")
네넵 이렇게 합시당

2024-07-01 13:46 UTC, eeddiinn commented on src/main/java/com/roomcatcher/RoomCatcher/domain/Product.java
> +    @Column(nullable = false)
String으로 들어가는게 이름, 성별, 주소 등 딱 정해져있는것들이여서 길이 제한을 딱히 안하긴 했는데 ! 하는게 좋을까요 ?! 
그리고 Length로 제한한다면  Product엔티티는 매물 기타 정보의 길이가 얼마나 될지 아직 잘 모르겠어서 나중에 데이터 구조를 확인한 후 추가하는게 좋을 것 같습니당 !

2024-07-02 09:20 UTC, 5hseok commented on src/main/java/com/roomcatcher/RoomCatcher/domain/Product.java
> +    @Column(nullable = false)
조아요

2024-07-02 09:21 UTC, 5hseok approved these changes
리뷰 사항 확인했습니다. 머지해도 될 것 같아요.

2024-07-02 09:22 UTC, merged